project:
  type: website

website:
  title: "tarleb"
  description: "tarleb's blog"
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - imprint.qmd
      - href: index.xml
        icon: rss
  open-graph: true
  site-url: 'https://tarleb.com'
  site-path: '/'
  twitter-card:
    creator: '@_tarleb'

format:
  html:
    theme: minty
    css: styles.css
    toc: true

filters:
  - _extensions/address.lua
  - _extensions/css-mailto-obfuscation.lua
